//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokenizer4GA.Shared.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Tokenizer4GA.Shared.Localization.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        public static string AddCertificate {
            get {
                return ResourceManager.GetString("AddCertificate", resourceCulture);
            }
        }
        
        public static string CertificateTitlePage {
            get {
                return ResourceManager.GetString("CertificateTitlePage", resourceCulture);
            }
        }
        
        public static string InfoCertificate {
            get {
                return ResourceManager.GetString("InfoCertificate", resourceCulture);
            }
        }
        
        public static string PreventDataLossBackConfirmation {
            get {
                return ResourceManager.GetString("PreventDataLossBackConfirmation", resourceCulture);
            }
        }
        
        public static string IncorrectFormatServiceResponse {
            get {
                return ResourceManager.GetString("IncorrectFormatServiceResponse", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        public static string CallError {
            get {
                return ResourceManager.GetString("CallError", resourceCulture);
            }
        }
        
        public static string SharedError {
            get {
                return ResourceManager.GetString("SharedError", resourceCulture);
            }
        }
        
        public static string MessageNotInternet {
            get {
                return ResourceManager.GetString("MessageNotInternet", resourceCulture);
            }
        }
        
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string NoInternetLogin {
            get {
                return ResourceManager.GetString("NoInternetLogin", resourceCulture);
            }
        }
        
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        public static string ResendRegisterEmail {
            get {
                return ResourceManager.GetString("ResendRegisterEmail", resourceCulture);
            }
        }
        
        public static string RegisterUncompleted {
            get {
                return ResourceManager.GetString("RegisterUncompleted", resourceCulture);
            }
        }
        
        public static string ExtensionErrorCertificate {
            get {
                return ResourceManager.GetString("ExtensionErrorCertificate", resourceCulture);
            }
        }
        
        public static string NullErrorCertificate {
            get {
                return ResourceManager.GetString("NullErrorCertificate", resourceCulture);
            }
        }
    }
}
