//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tokenizer4GA.Shared.WebServices.Mocks {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Base64Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Base64Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tokenizer4GA.Shared.WebServices.Mocks.Base64Resources", typeof(Base64Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDABcQERQRDhcUEhQaGBcbIjklIh8fIkYyNSk5UkhXVVFIUE5bZoNvW2F8Yk5QcptzfIeLkpSSWG2grJ+OqoOPko3/2wBDARgaGiIeIkMlJUONXlBejY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY3/wAARCALuBTIDAREAAhEBAxEB/8QAGgABAAMBAQEAAAAAAAAAAAAAAAECAwQFBv/EAE0QAAEDAwIDBAYGCAQFAwMEAwEAAhEDBCESMQVBURMiYXEGFDJSgZEVIzNCobE0U1RicpLB0UNjouEkNYLw8RYlczZEsiaDk6PCVeL/xAAZAQEBAQEBAQAAAAAAAAAAAAAAAQIDBAX/xAAxEQEBAAIBAwQBBAIDAQACAgMAAQIRIQMSMRNBUWFxBBQiMmKBM0KhsSPBQ1KRcvD/2gAMAwEAAhEDEQA/APrEBAQEBAQE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string DrivingLicense {
            get {
                return ResourceManager.GetString("DrivingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /9j/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAQrBkADASIAAhEBAxEB/8QAHAAAAgMBAQEBAAAAAAAAAAAAAQIAAwQFBgcI/8QAVBAAAQMCBAMGAgYHBwEGBAILAQACEQMhBBIxQQVRYQYTInGBkTKhFEJSscHRBxUjYnKC4RYzQ1OS8PEkJTREY3OiFzVUg5NFVbImZHSEVsKUo9L/xAAZAQEBAQEBAQAAAAAAAAAAAAAAAQIDBAX/xAAnEQEBAQACAgICAgMBAQEBAAAAARECEiExAxNBUSJhBDJxFEIjgf/aAAwDAQACEQMRAD8A4O+ikjVLEz5qTPNFEi3iHoEDbooLBE3sN0Ay [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string FordFusion {
            get {
                return ResourceManager.GetString("FordFusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JVBERi0xLjcKCjQgMCBvYmoKKElkZW50aXR5KQplbmRvYmoKNSAwIG9iagooQWRvYmUpCmVuZG9iago4IDAgb2JqCjw8Ci9GaWx0ZXIgL0ZsYXRlRGVjb2RlCi9MZW5ndGggNjc4ODQKL0xlbmd0aDEgMzQ0NzcyCi9UeXBlIC9TdHJlYW0KPj4Kc3RyZWFtCnic7H0JYNTF9f+b73evZLNH7s25381mk5DdZHNxJESyOSEkkJgESBAkm2QhgZCEHCBWBW+NF7VUa2sVW7W22roE1IitUovWC8WjolYBFa0XllrPCtn/m9nNJiGRSv+0vwDzmXzfvLln3sy8OfabXSAAEIVEBptKastnt17WkAdyix4gbvvsktKy4E0Rz4HwQD2AmDe7uqpWdDxwCwiDm4Ecen927YKi30QfdYHs7gsALgqbW1tXtjq1TQHyxE2Ya3xlXe2cc/dlPwpQvAsg5OyqWntWZMdFZQCCAcMbq4sr6xpevvhdzF9C97SFJfPq [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string InsurancePolicy {
            get {
                return ResourceManager.GetString("InsurancePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /9j/4AAQSkZJRgABAQEBLAEsAAD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wgARCAUAB4ADASIAAhEBAxEB/8QAGwAAAwEBAQEBAAAAAAAAAAAAAAECAwQFBgf/xAAaAQEBAQEBAQEAAAAAAAAAAAAAAQIDBAUG/9oADAMBAAIQAxAAAAH2gOWqEwAoaBgQNOgENoAFTcuGIGholU000AIYgYgpwyyXLVQ4shrTkloQMGJgoAMCAAQAACmkJUqQ2IbgYDqRdLypdayutXFJpplSbaY3rO15aalg7EwsABAAAAAAAmCAAAAAAAGJgAAAAAAAMAAAAAAAGCCaUZRpnNRNRnSlzLMWiZpQk0E2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string JeepGrandCherokee {
            get {
                return ResourceManager.GetString("JeepGrandCherokee", resourceCulture);
            }
        }
    }
}
